services:
  postgres:
    build: .
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
